/* Boot profiler, built only with PROF=1. Entry hooks on OS functions (prof_tramp.S, generated by
 * tools/gen_prof.py) time every call made by any task from the Music app init to the end of the
 * library load: call count, inclusive and exclusive time, longest call (microseconds), and which
 * tasks called it. Each task has its own call stack. */
#include "e.h"

extern const uint32_t prof_n, prof_addr[], prof_w0[], prof_hk[];
extern void prof_ret(void);
#define os_dcache_clean ((void (*)(void))0x0802ce00)

/* The hooks are written into the OS code in RAM only while profiling runs, so nothing that
   executes before the Music app init ever passes through them. */
static int installed;
static void prof_patch(int on_)
{
    uint32_t i, n = prof_n;
    if (on_) installed = 0;
    for (i = 0; i < n; i++) {
        volatile uint32_t *at = (volatile uint32_t *)prof_addr[i];
        uint32_t b = 0xea000000 | (((prof_hk[i] - prof_addr[i] - 8) >> 2) & 0xffffff);
        if (on_ && *at == prof_w0[i]) { *at = b; installed++; }
        else if (!on_ && *at == b) *at = prof_w0[i];
    }
    os_dcache_clean();
    __asm__ volatile("mov r0, #0\n mcr p15, 0, r0, c7, c10, 4\n mcr p15, 0, r0, c7, c5, 0" ::: "r0", "memory");
}

#define MAXF  4096
#define POOL  512
struct pst { uint32_t count, incl, excl, max, tasks; };
static struct pst st[MAXF];
static struct { uint32_t count, incl, excl; } wst[MAXF];   /* the same, counted only after the library load */
/* Calls in flight, all tasks together. A timed call is found again by the stack pointer it
   returns with, which equals the one it was entered with; the running-task word can change
   inside a call (context switches), the stack pointer of the returning call cannot. */
struct fr { uint32_t sp, idx, lr, t0, child; int parent; uint16_t gen, pgen; uint8_t tn; };
static struct fr pool[POOL];
static int act[POOL], nact, freel[POOL], nfree = -1;
static int16_t top[256];
static uint16_t gen;
static int on, overflow, notask, maxact, ntask;
static uint32_t t_start, overhead_ns, taskseen[8];
static char marks[1024]; static int nmarks;
/* every call that took 5 ms or more, in the order they ended: the boot's timeline */
#define NLONG 2000
struct lng { uint32_t idx, tn, t0, el, lr; };
static struct lng longs[NLONG];
static int nlong;

static uint32_t cur_task(void)
{
    uint32_t t = *(volatile uint32_t *)0x2200acf4;      /* RTXC running TCB */
    if ((t & 3) || ((t >> 24) != 0x22 && (t >> 26) != 2)) return 0xff;
    return *(volatile uint32_t *)(t + 32) & 0xff;
}

static void pool_reset(void)
{
    int k;
    nact = 0;
    for (k = 0; k < POOL; k++) freel[k] = POOL - 1 - k;
    nfree = POOL;
    for (k = 0; k < 256; k++) top[k] = -1;
}

/* callers of the device read and the FAT entry read after the library load */
#define NCALLER 64
static struct { uint32_t fn, lr, n; } callers[NCALLER];
int krec_on;
#define NTRACE 24000
static uint32_t *trace; static int ntrace;   /* {time us, idx | task << 16} for every timed entry in the window */
uint32_t kwin = 0xffffffffu;      /* untimed records from here (set after the library load) */
static void callers_add(uint32_t fn, uint32_t lr)
{
    int k;
    if (fn != 0x082bb36c && fn != 0x082d5dd4 && fn != 0x080746ec && fn != 0x0826deec && fn != 0x082d90c0) return;
    for (k = 0; k < NCALLER; k++) {
        if (callers[k].fn == fn && callers[k].lr == lr) { callers[k].n++; return; }
        if (!callers[k].fn) { callers[k].fn = fn; callers[k].lr = lr; callers[k].n = 1; return; }
    }
}

/* frame: the trampoline's saved r0-r3, ip, lr; the function's own stack pointer is just above */
uint32_t prof_enter(uint32_t i, uint32_t *frame)
{
    uint32_t cpsr, tn, irq;
    struct fr *f;
    int slot;
    if (!on) return 0;
    __asm__ volatile("mrs %0, cpsr" : "=r"(cpsr));
    if ((cpsr & 0x1f) == 0x12 || (cpsr & 0x1f) == 0x11) return 0;          /* IRQ, FIQ */
    __asm__ volatile("mrs %0, cpsr\n orr %1, %0, #0xc0\n msr cpsr_c, %1" : "=r"(irq), "=r"(tn));   /* no interrupts while the pool changes */
    tn = cur_task();
    if (tn == 0xff) { notask++; __asm__ volatile("msr cpsr_c, %0" :: "r"(irq)); return 0; }
    if (!nfree) { overflow++; __asm__ volatile("msr cpsr_c, %0" :: "r"(irq)); return 0; }
    slot = freel[--nfree];
    f = &pool[slot];
    f->sp = (uint32_t)frame + 24; f->idx = i; f->lr = frame[5]; f->child = 0; f->tn = tn;
    if (!++gen) gen = 1;
    f->gen = gen; f->parent = top[tn]; f->pgen = f->parent >= 0 ? pool[f->parent].gen : 0;
    top[tn] = slot;
    act[nact++] = slot;
    if (nact > maxact) maxact = nact;
    if (!(taskseen[tn >> 5] & (1u << (tn & 31)))) { taskseen[tn >> 5] |= 1u << (tn & 31); ntask++; }
    st[i].tasks |= 1u << (tn & 31);
    if (krec_on) callers_add(prof_addr[i], frame[5]);
    if (trace) { uint32_t now = TIMER_E; if (now >= kwin) { int k = ntrace++ % NTRACE; trace[2 * k] = now; trace[2 * k + 1] = i | tn << 16; } }   /* ring: the last NTRACE calls */
    frame[5] = (uint32_t)prof_ret;
    f->t0 = TIMER_E;
    __asm__ volatile("msr cpsr_c, %0" :: "r"(irq));
    return 1;
}

/* from prof_ret with the returning call's stack pointer: closes that call, gives its return address */
uint32_t prof_exit(uint32_t sp)
{
    uint32_t now = TIMER_E, el, lr, irq, tmp;
    struct fr *f;
    struct pst *s;
    int k, slot;
    __asm__ volatile("mrs %0, cpsr\n orr %1, %0, #0xc0\n msr cpsr_c, %1" : "=r"(irq), "=r"(tmp));
    for (k = nact - 1; k >= 0 && pool[act[k]].sp != sp; k--) ;
    if (k < 0) { for (;;) ; }                    /* only timed calls return here */
    slot = act[k];
    for (; k < nact - 1; k++) act[k] = act[k + 1];
    nact--;
    f = &pool[slot];
    el = now - f->t0;
    s = &st[f->idx];
    s->count++; s->incl += el; s->excl += el > f->child ? el - f->child : 0;
    if (krec_on) { wst[f->idx].count++; wst[f->idx].incl += el; wst[f->idx].excl += el > f->child ? el - f->child : 0; }
    if (el > s->max) s->max = el;
    if (el >= 5000 && nlong < NLONG) { struct lng *g = &longs[nlong++]; g->idx = f->idx; g->tn = f->tn; g->t0 = f->t0; g->el = el; g->lr = f->lr; }
    if (f->parent >= 0 && pool[f->parent].gen == f->pgen) pool[f->parent].child += el;
    if (top[f->tn] == slot) top[f->tn] = f->parent >= 0 && pool[f->parent].gen == f->pgen ? f->parent : -1;
    lr = f->lr;
    f->gen = 0;
    freel[nfree++] = slot;
    __asm__ volatile("msr cpsr_c, %0" :: "r"(irq));
    return lr;
}

/* a timestamped label in the dump */
void prof_mark(const char *what)
{
    int k = 0;
    char num[12]; int nn = 0; uint32_t v = TIMER_E / 1000;
    do { num[nn++] = '0' + v % 10; v /= 10; } while (v);
    while (nn && nmarks < (int)sizeof marks - 2) marks[nmarks++] = num[--nn];
    if (nmarks < (int)sizeof marks - 2) marks[nmarks++] = ' ';
    while (what[k] && nmarks < (int)sizeof marks - 2) marks[nmarks++] = what[k++];
    marks[nmarks++] = '\n'; marks[nmarks] = 0;
}

void prof_start(void)
{
    uint32_t frame[6], t;
    int k;
    memset(st, 0, sizeof st);
    pool_reset();
    overflow = 0; notask = 0;
    on = 1;
    /* cost of one timed call without the trampoline's few instructions */
    t = TIMER_E;
    for (k = 0; k < 1000; k++) { frame[5] = 0; if (prof_enter(0, frame)) prof_exit((uint32_t)frame + 24); }
    overhead_ns = TIMER_E - t;
    memset(st, 0, sizeof st);
    memset(taskseen, 0, sizeof taskseen); ntask = 0; maxact = 0; nlong = 0;
    trace = os_malloc(NTRACE * 8); ntrace = 0;
    { void samp_start(void); samp_start(); }
    prof_patch(1);
    t_start = TIMER_E;
    prof_mark("profiling on");
}

void prof_stop(int load)
{
    static char name[] = "FLAC\\loadprof0.bin";
    uint32_t total = TIMER_E - t_start, n = prof_n < MAXF ? prof_n : MAXF, i, k, *buf, sz;
    int top[15], j;
    static int stopped;
    if (stopped) return;
    stopped = 1;
    { void samp_stop(void); samp_stop(); }
    on = 0;
    prof_patch(0);
    prof_mark("profiling off");
    sz = 32 + n * 24 + sizeof marks + 4 + NLONG * sizeof(struct lng);
    buf = os_malloc(sz);
    if (buf) {
        buf[0] = 0x33465250; buf[1] = n; buf[2] = total; buf[3] = overhead_ns; buf[4] = overflow; buf[5] = notask; buf[6] = t_start; buf[7] = 0;
        for (i = 0; i < n; i++) {
            uint32_t *e = buf + 8 + i * 6;
            e[0] = prof_addr[i]; e[1] = st[i].count; e[2] = st[i].incl; e[3] = st[i].excl; e[4] = st[i].max; e[5] = st[i].tasks;
        }
        memcpy(buf + 8 + n * 6, marks, sizeof marks);
        buf[8 + n * 6 + sizeof marks / 4] = nlong;
        memcpy(buf + 8 + n * 6 + sizeof marks / 4 + 1, longs, sizeof longs);
        name[13] = '0' + (load % 10);
        vol_delete(name);
        file_write(name, buf, sz);
        os_free(buf);
    }
    if (trace) {
        uint32_t *tb = trace;
        trace = 0;
        tb[0] = tb[0];   /* entries start at index 0; the count goes in the log */
        vol_delete("FLAC\\trace1.bin");
        file_write("FLAC\\trace1.bin", tb, (uint32_t)(ntrace < NTRACE ? ntrace : NTRACE) * 8);
        log_s("   trace: "); log_d(ntrace); log_s(" calls from "); log_d((int)(kwin / 1000)); log_s(" ms\n");
    }
    log_s("   prof: "); log_d((int)n); log_s(" functions, profiled "); log_d((int)(total / 1000)); log_s(" ms, hook cost ");
    log_d((int)overhead_ns); log_s(" ns/call, overflow "); log_d(overflow); log_s(", tasks "); log_d(ntask); log_s(", deepest "); log_d(maxact); log_s(", hooks installed "); log_d(installed); log_s(", top by own time:\n");
    for (j = 0; j < 15; j++) {
        int best = -1;
        for (i = 0; i < n; i++) {
            int used = 0;
            for (k = 0; k < (uint32_t)j; k++) if (top[k] == (int)i) used = 1;
            if (!used && (best < 0 || st[i].excl > st[best].excl)) best = (int)i;
        }
        top[j] = best;
        if (best < 0 || !st[best].count) break;
        log_s("     "); log_x(prof_addr[best], 8); log_s(" own "); log_d((int)(st[best].excl / 1000)); log_s(" ms, total ");
        log_d((int)(st[best].incl / 1000)); log_s(" ms, calls "); log_d((int)st[best].count); log_s(", longest ");
        log_d((int)st[best].max); log_s(" us\n");
    }
    { void kdump(void); kdump(); }
}

/* boot timers: each software timer that fires between 1 s and 12 s, by the timer service
   (task 4, 0x080847e8): the timer object, its fields, and the callback or the message it posts */
static int tlog_n;
static void tlog(const char *how, uint32_t *t, uint32_t a, uint32_t b)
{
    uint32_t ms = TIMER_E / 1000;
    int k;
    if (ms < 1000 || ms > 12000 || tlog_n >= 48) return;
    tlog_n++;
    log_s("   timer "); log_s(how); log_s(" at "); log_d((int)ms); log_s(" ms: obj "); log_x((uint32_t)t, 8);
    log_s(" "); log_x(a, 8); log_s(" "); log_x(b, 8); log_s(" fields");
    for (k = 0; k < 10; k++) { log_c(' '); log_x(t[k], 8); }
    log_c('\n');
}
static void __attribute__((used)) tpost_c(uint32_t *r) { tlog("msg", (uint32_t *)r[2], r[0], r[1]); }
static void __attribute__((used)) tcb_c(uint32_t *r) { tlog("cb ", (uint32_t *)r[0], r[1], 0); }
__attribute__((naked, section(".text.entry"), used)) void hk_tpost(void)
{
    __asm__ volatile("push {r0-r3, ip, lr}\n mov r0, sp\n bl tpost_c\n pop {r0-r3, ip, lr}\n ldr pc, 1f\n 1: .word 0x080e62a4\n");
}
__attribute__((naked, section(".text.entry"), used)) void hk_tcb(void)
{
    __asm__ volatile("push {r0-r3, ip, lr}\n mov r0, sp\n bl tcb_c\n pop {r0-r3, ip, lr}\n bx r1\n");
}

/* kernel calls from 2 s until the profiler stops: sleep(ms) 0x0802cfb0, event wait with
   timeout 0x0802cfc8, event post 0x0802cfa8 (their veneer literals point here), and message
   post 0x080e62a4 (entry hook). Task context only; dumped by prof_stop. */
struct kev { uint32_t t, kind, lr, a0, a1, tn, n; };
static struct kev kev[150];
static int nkev;
void __attribute__((used)) krec(uint32_t kind, uint32_t lr, uint32_t a0, uint32_t a1)
{
    uint32_t cpsr, irq, tmp, t = TIMER_E;
    if (!on || !krec_on || t < kwin || nkev >= (int)(sizeof kev / sizeof kev[0])) return;
    __asm__ volatile("mrs %0, cpsr" : "=r"(cpsr));
    if ((cpsr & 0x1f) == 0x12 || (cpsr & 0x1f) == 0x11) return;
    __asm__ volatile("mrs %0, cpsr\n orr %1, %0, #0xc0\n msr cpsr_c, %1" : "=r"(irq), "=r"(tmp));
    {
        uint32_t tn = cur_task();
        struct kev *l = nkev ? &kev[nkev - 1] : 0;
        if (l && l->kind == kind && l->lr == lr && l->tn == tn) l->n++;
        else if (nkev < (int)(sizeof kev / sizeof kev[0])) { struct kev *k = &kev[nkev++]; k->t = t; k->kind = kind; k->lr = lr; k->a0 = a0; k->a1 = a1; k->tn = tn; k->n = 1; }
    }
    __asm__ volatile("msr cpsr_c, %0" :: "r"(irq));
}
static void wdump(void)
{
    int pass, j, k, i, n = prof_n < MAXF ? (int)prof_n : MAXF, top[25];
    for (pass = 0; pass < 2; pass++) {
        log_s(pass ? "   after the library load, by own time:\n" : "   after the library load, by total time:\n");
        for (j = 0; j < 25; j++) {
            int best = -1;
            for (i = 0; i < n; i++) {
                uint32_t v = pass ? wst[i].excl : wst[i].incl, b;
                int used = 0;
                for (k = 0; k < j; k++) if (top[k] == i) used = 1;
                if (used || !wst[i].count) continue;
                b = best < 0 ? 0 : (pass ? wst[best].excl : wst[best].incl);
                if (best < 0 || v > b) best = i;
            }
            top[j] = best;
            if (best < 0) break;
            log_s("     "); log_x(prof_addr[best], 8); log_s(" total "); log_d((int)(wst[best].incl / 1000)); log_s(" ms, own ");
            log_d((int)(wst[best].excl / 1000)); log_s(" ms, calls "); log_d((int)wst[best].count); log_c('\n');
        }
    }
}
void kdump(void)
{
    wdump();
}
/* sleep and event wait, timed around the real call: blocks of 20 ms or more after the library load */
void __attribute__((used)) krec2(uint32_t kind, uint32_t lr, uint32_t t0, uint32_t a)
{
    uint32_t el = TIMER_E - t0, irq, tmp, tn;
    if (!on || !krec_on || el < 20000 || lr == 0x0804ba5c || nkev >= (int)(sizeof kev / sizeof kev[0])) return;   /* not the timer service's own wait */
    tn = cur_task();
    __asm__ volatile("mrs %0, cpsr\n orr %1, %0, #0xc0\n msr cpsr_c, %1" : "=r"(irq), "=r"(tmp));
    if (nkev < (int)(sizeof kev / sizeof kev[0])) { struct kev *k = &kev[nkev++]; k->t = t0; k->kind = kind; k->lr = lr; k->a0 = a; k->a1 = el / 1000; k->tn = tn; k->n = 1; }
    __asm__ volatile("msr cpsr_c, %0" :: "r"(irq));
}
#define KTIMED(name, kind, target, areg) \
__attribute__((naked, section(".text.entry"), used)) void name(void) \
{ __asm__ volatile("push {r0-r6, lr}\n ldr r4, 2f\n ldr r4, [r4]\n mov r5, " #areg "\n ldr ip, 1f\n blx ip\n" \
                   "str r0, [sp]\n str r1, [sp, #4]\n mov r0, #" #kind "\n ldr r1, [sp, #28]\n mov r2, r4\n mov r3, r5\n bl krec2\n" \
                   "pop {r0-r6, lr}\n bx lr\n 1: .word " #target "\n 2: .word 0x3c7000b4\n"); }
KTIMED(hk_ksleep, 1, 0x22003d44, r1)
KTIMED(hk_kwait, 2, 0x220043c0, r0)
KTIMED(hk_ksemw, 6, 0x22004368, r0)
#define KVENEER(name, kind, target) \
__attribute__((naked, section(".text.entry"), used)) void name(void) \
{ __asm__ volatile("push {r0-r3, ip, lr}\n mov r2, r0\n mov r3, r1\n mov r1, lr\n mov r0, #" #kind "\n bl krec\n" \
                   "pop {r0-r3, ip, lr}\n ldr pc, 1f\n 1: .word " #target "\n"); }
KVENEER(hk_kpost, 3, 0x22001cbc)
KVENEER(hk_ksig, 4, 0x220043f4)
KVENEER(hk_ksig2, 5, 0x22004260)
__attribute__((naked, section(".text.entry"), used)) void hk_mpost(void)
{
    __asm__ volatile("push {r0-r3, ip, lr}\n mov r2, r0\n mov r3, r1\n mov r1, lr\n mov r0, #4\n bl krec\n"
                     "pop {r0-r3, ip, lr}\n .word 0xe92d401c\n ldr pc, 1f\n 1: .word 0x080e62a8\n");
}

/* file opens between the library load and the UI: 0x0826deec(stream, ?, mode, path) */
static int nopen;
static void __attribute__((used)) fopen_c(uint32_t *r)
{
    const char *p = (const char *)r[3];
    int k;
    if (!krec_on || !on || nopen >= 80) return;
    nopen++;
    log_s("   open "); log_d((int)(TIMER_E / 1000)); log_s(" ms from "); log_x(r[7], 8); log_s(": ");
    if ((uint32_t)p >= 0x08000000 && (uint32_t)p < 0x0c000000) for (k = 0; k < 90 && p[k]; k++) log_c(p[k] >= 32 && p[k] < 127 ? p[k] : '?');
    else log_x((uint32_t)p, 8);
    log_c('\n');
}
__attribute__((naked, section(".text.entry"), used)) void hk_fopen(void)
{
    __asm__ volatile(
        "push {r0-r5, ip, lr}\n mov r0, sp\n ldr ip, 1f\n mov lr, pc\n bx ip\n"
        "pop {r0-r5, ip, lr}\n"
        ".word 0xe92d41f0\n ldr pc, 2f\n"
        "1: .word fopen_c\n 2: .word 0x0826def0\n");
}

/* PC + stack sampler: Apple's IRQ entry (IRAM 0x22003080) jumps here first. Each entry: the
   interrupted PC, the time, the running TCB, the interrupted SVC-mode lr and sp, then 48 words of
   that stack (return addresses on it give the call chain). Ring in the heap, written by prof_stop. */
uint32_t *samp_buf;                    /* [0] = count, [1] unused, then NSAMP entries of 53 words */
#define NSAMP 3072
#define SWORDS 53
__attribute__((naked, section(".text.entry"), used)) void hk_irqs(void)
{
    __asm__ volatile(
        "sub lr, lr, #4\n str lr, [sp, #-12]\n"
        "str r0, [sp, #-16]\n str r1, [sp, #-20]\n str r2, [sp, #-24]\n str r3, [sp, #-28]\n"
        "ldr r1, 1f\n ldr r1, [r1]\n cmp r1, #0\n beq 9f\n"
        "ldr r0, [r1]\n add r2, r0, #1\n str r2, [r1]\n"
        "ldr r2, 4f\n"                                   /* r0 % NSAMP without a divide: NSAMP = 3072 = 3 << 10 */
        "8: cmp r0, r2\n subcs r0, r0, r2\n bcs 8b\n"
        "mov r2, #212\n mul r3, r0, r2\n add r2, r1, #8\n add r2, r2, r3\n"   /* entry = buf + 8 + i * 212 */
        "str lr, [r2]\n ldr r0, 2f\n ldr r0, [r0]\n str r0, [r2, #4]\n"
        "ldr r0, 5f\n ldr r0, [r0]\n str r0, [r2, #8]\n"
        "mrs r3, cpsr\n msr cpsr_c, #0xd3\n mov r0, sp\n mov r1, lr\n msr cpsr_c, r3\n"   /* SVC sp and lr */
        "str r1, [r2, #12]\n str r0, [r2, #16]\n"
        "add r2, r2, #20\n mov r3, #48\n"
        "7: ldr r1, [r0], #4\n str r1, [r2], #4\n subs r3, r3, #1\n bne 7b\n"
        "9: ldr r0, [sp, #-16]\n ldr r1, [sp, #-20]\n ldr r2, [sp, #-24]\n ldr r3, [sp, #-28]\n"
        "ldr pc, 3f\n"
        "1: .word samp_buf\n 2: .word 0x3c7000b4\n 3: .word 0x22003088\n 4: .word 3072\n 5: .word 0x2200acf4\n");
}
void samp_start(void) { uint32_t *b = os_malloc(8 + NSAMP * SWORDS * 4); if (b) { b[0] = 0; b[1] = 0; samp_buf = b; } }
void samp_stop(void)
{
    uint32_t *b = samp_buf, n;
    if (!b) return;
    samp_buf = 0;
    n = b[0] < NSAMP ? b[0] : NSAMP;
    vol_delete("FLAC\\samples.bin");
    file_write("FLAC\\samples.bin", b, 8 + NSAMP * SWORDS * 4);
    log_s("   samples: "); log_d((int)b[0]); log_s(" interrupts, "); log_d((int)n); log_s(" kept\n");
}
