/* generated by host/gen_theme_data.py from the OS names table; do not edit */
/* chrome images: greys invert, Apple blue becomes the accent */
static const uint32_t theme_bmap_chrome[62] = {
    0x0dad0221, /* DateTimePicker_Selection */
    0x0dad06ff, /* Media_Genius_Selected_Image */
    0x0dad0863, /* NowPlaying_Idle_Battery_0_Image */
    0x0dad0864, /* NowPlaying_Idle_Battery_1_Image */
    0x0dad0865, /* NowPlaying_Idle_Battery_2_Image */
    0x0dad0866, /* NowPlaying_Idle_Battery_3_Image */
    0x0dad0867, /* NowPlaying_Idle_Battery_4_Image */
    0x0dad0868, /* NowPlaying_Idle_Battery_5_Image */
    0x0dad0869, /* NowPlaying_Idle_Battery_6_Image */
    0x0dad086a, /* NowPlaying_Idle_Battery_7_Image */
    0x0dad0862, /* NowPlaying_Idle_Colon_Image */
    0x0dad0858, /* NowPlaying_Idle_Digit_0_Image */
    0x0dad0859, /* NowPlaying_Idle_Digit_1_Image */
    0x0dad085a, /* NowPlaying_Idle_Digit_2_Image */
    0x0dad085b, /* NowPlaying_Idle_Digit_3_Image */
    0x0dad085c, /* NowPlaying_Idle_Digit_4_Image */
    0x0dad085d, /* NowPlaying_Idle_Digit_5_Image */
    0x0dad085e, /* NowPlaying_Idle_Digit_6_Image */
    0x0dad085f, /* NowPlaying_Idle_Digit_7_Image */
    0x0dad0860, /* NowPlaying_Idle_Digit_8_Image */
    0x0dad0861, /* NowPlaying_Idle_Digit_9_Image */
    0x0dad086b, /* NowPlaying_Idle_Lock_Image */
    0x0dad086c, /* NowPlaying_Idle_Play_Image */
    0x0dad086d, /* NowPlaying_Idle_Radio_Image */
    0x0dad084d, /* NowPlaying_ProgressBar_Active_Background_Image */
    0x0dad084e, /* NowPlaying_ProgressBar_Active_Fill_Image */
    0x0dad0841, /* NowPlaying_ProgressBar_Growth_Image */
    0x0dad084b, /* NowPlaying_ProgressBar_Inactive_Background_Image */
    0x0dad084c, /* NowPlaying_ProgressBar_Inactive_Fill_Image */
    0x0dad083f, /* NowPlaying_ProgressBar_LeftEndcap_Image */
    0x0dad0840, /* NowPlaying_ProgressBar_RightEndcap_Image */
    0x0dad084f, /* NowPlaying_ProgressBar_Scrub_Image */
    0x0dad0844, /* NowPlaying_ProgressFill_Growth_Image */
    0x0dad0842, /* NowPlaying_ProgressFill_LeftEndcap_Image */
    0x0dad0843, /* NowPlaying_ProgressFill_RightEndcap_Image */
    0x0dad083d, /* NowPlaying_White_FF_Image */
    0x0dad0839, /* NowPlaying_White_Pause_Image */
    0x0dad083a, /* NowPlaying_White_Play_Image */
    0x0dad083e, /* NowPlaying_White_Rew_Image */
    0x0dad0855, /* NowPlaying_White_Volume_High_Image */
    0x0dad0857, /* NowPlaying_White_Volume_Locked_Image */
    0x0dad0854, /* NowPlaying_White_Volume_Low_Image */
    0x0dad0151, /* OptionBar_White_Thumb_Center_Image */
    0x0dad0150, /* OptionBar_White_Thumb_LeftCap_Image */
    0x0dad0152, /* OptionBar_White_Thumb_RightCap_Image */
    0x0dad014e, /* OptionBar_White_Well_Center_Image */
    0x0dad014d, /* OptionBar_White_Well_LeftCap_Image */
    0x0dad014f, /* OptionBar_White_Well_RightCap_Image */
    0x0dad0bcd, /* Settings_MainMenu_CheckmarkBlack_Image */
    0x0dad0bce, /* Settings_MainMenu_CheckmarkWhite_Image */
    0x0dad00f6, /* StatusBarWhite_Background_Image */
    0x0dad010e, /* StatusBarWhite_Lock_Image */
    0x0dad00f7, /* StatusBarWhite_PlayStatus_Image */
    0x0dad0149, /* System_ActiveButtonFill_Image */
    0x0dad0147, /* System_ActiveButtonLeftCap_Image */
    0x0dad0148, /* System_ActiveButtonRightCap_Image */
    0x0dad014c, /* System_NormalButtonFill_Image */
    0x0dad014a, /* System_NormalButtonLeftCap_Image */
    0x0dad014b, /* System_NormalButtonRightCap_Image */
    0x0dad00f0, /* System_ScrollbarBottom_Image */
    0x0dad00ef, /* System_ScrollbarCenter_Image */
    0x0dad00ee, /* System_ScrollbarTop_Image */
};
/* backgrounds: luminance squeezed into the dark range */
static const uint32_t theme_bmap_bg[4] = {
    0x0dad00f9, /* Background_LightBlue_Image */
    0x0dad0220, /* DateTimePicker_Bar */
    0x0dad0222, /* DateTimePicker_Well */
    0x0dad0709, /* GeniusMixes_Background_Image */
};
/* accent icons: every coloured pixel takes the accent hue, in both themes */
static const uint32_t theme_bmap_accent[25] = {
    0x0dad010f, /* StatusBarWhite_Battery_Image_0 */
    0x0dad0110, /* StatusBarWhite_Battery_Image_1 */
    0x0dad0119, /* StatusBarWhite_Battery_Image_10 */
    0x0dad011a, /* StatusBarWhite_Battery_Image_11 */
    0x0dad011b, /* StatusBarWhite_Battery_Image_12 */
    0x0dad011c, /* StatusBarWhite_Battery_Image_13 */
    0x0dad011d, /* StatusBarWhite_Battery_Image_14 */
    0x0dad011e, /* StatusBarWhite_Battery_Image_15 */
    0x0dad011f, /* StatusBarWhite_Battery_Image_16 */
    0x0dad0120, /* StatusBarWhite_Battery_Image_17 */
    0x0dad0121, /* StatusBarWhite_Battery_Image_18 */
    0x0dad0122, /* StatusBarWhite_Battery_Image_19 */
    0x0dad0111, /* StatusBarWhite_Battery_Image_2 */
    0x0dad0123, /* StatusBarWhite_Battery_Image_20 */
    0x0dad0124, /* StatusBarWhite_Battery_Image_21 */
    0x0dad0125, /* StatusBarWhite_Battery_Image_22 */
    0x0dad0112, /* StatusBarWhite_Battery_Image_3 */
    0x0dad0113, /* StatusBarWhite_Battery_Image_4 */
    0x0dad0114, /* StatusBarWhite_Battery_Image_5 */
    0x0dad0115, /* StatusBarWhite_Battery_Image_6 */
    0x0dad0116, /* StatusBarWhite_Battery_Image_7 */
    0x0dad0117, /* StatusBarWhite_Battery_Image_8 */
    0x0dad0118, /* StatusBarWhite_Battery_Image_9 */
    0x0dad0127, /* StatusBarWhite_Battery_Image_Charge */
    0x0dad0126, /* StatusBarWhite_Battery_Image_Plug */
};
/* COLR entries the dark theme changes (stock value in the comment) */
static const uint32_t theme_colr[42] = {
    0x0dad0045, /* SettingsLegal_Color_Gray #474747 */
    0x0dad0097, /* Settings_Color_White #FFFFFF */
    0x0dad0099, /* Background_Color #FFFFFF */
    0x0dad009a, /* System_Text_Color #000000 */
    0x0dad009b, /* System_Blue_Text_Color #236CC4 */
    0x0dad0234, /* AddressViewer_ContactDetails_Divider_Color #D3D3D3 */
    0x0dad0235, /* AddressViewer_Foreground_Color #FFFFFF */
    0x0dad0236, /* AddressViewer_Details_White #FFFFFF */
    0x0dad0237, /* AddressViewer_Details_Grey #BBBBBB */
    0x0dad0272, /* Alarms_Alert_Color #000000 */
    0x0dad02db, /* Settings_DateTime_DayNumeric_Color #000000 */
    0x0dad0312, /* Calendar_Weekday_Text_Color #666666 */
    0x0dad0313, /* Calendar_Active_Text_Color #000000 */
    0x0dad0314, /* Calendar_InActive_Text_Color #666666 */
    0x0dad0315, /* Calendar_Event_Header_Color #666666 */
    0x0dad0316, /* Calendar_Event_Data_Color #000000 */
    0x0dad05a0, /* CoverFlow_AlbumInfo_Text_Color #000000 */
    0x0dad05a1, /* CoverFlow_Classic_Text_Color #333333 */
    0x0dad0684, /* MediaList_Color_Gray #FFFFFF */
    0x0dad0685, /* GeniusMixes_Color_Gray #A4A4A4 */
    0x0dad081b, /* NowPlaying_White_Text_Color #000000 */
    0x0dad081c, /* NowPlaying_White_SubText_Color #3D3D3D */
    0x0dad081d, /* NowPlaying_Idle_Background #FFFFFF */
    0x0dad0954, /* RentalInfo_ExpirationTimeRemaining_Text_Color #176EC1 */
    0x0dad0955, /* RentalInfo_ExpiringSoon_Text_Color #FF0000 */
    0x0dad099f, /* Notes_Loading_BG_Color #FFFFFF */
    0x0dad0b3e, /* Settings_Icon_Color #D7D7D7 */
    0x0dad0b3f, /* Settings_Color_Black #000000 */
    0x0dad0b40, /* Settings_Color_Gray #EEEEEE */
    0x0dad0b41, /* SettingsSubtitle_Color_Gray #AEBAC1 */
    0x0dad0c80, /* Stopwatch_Text_Color #FFFFFF */
    0x0dad0c81, /* Stopwatch_Lap1_Color #9BA9B8 */
    0x0dad0c82, /* Stopwatch_Lap2_Color #717D88 */
    0x0dad0c83, /* Stopwatch_Lap3_Color #5E686F */
    0x0dad0c84, /* Stopwatch_Session_Date_Background_Color #CDDCF3 */
    0x0dad0c85, /* Stopwatch_Session_Div1_Background_Color #C5C5C5 */
    0x0dad0c86, /* Stopwatch_Session_Div2_Background_Color #E5E5E5 */
    0x0dad0c87, /* Stopwatch_Session_Stats_Background_Color #F5F5F5 */
    0x0dad0c88, /* Stopwatch_Session_Label_Color #959595 */
    0x0dad0d3f, /* VoiceMemos_MemoNameTextColor #000000 */
    0x0dad0d40, /* VoiceMemos_MemoDateTextColor #000000 */
    0x0dad0d8e, /* Search_EditBox_Background_Color #FFFFFF */
};
