#!/usr/bin/env python3
"""Writes runtime/theme_data.h: the resource ids the dark theme touches, picked from the OS
names table with the same rules as theme_preview.py.  gen_theme_data.py OSOS.dec OUT.h"""
import struct, sys
from uires import Package, DATA, BASE
from theme_preview import BMAP_PREFIX, COLR_KEEP_PREFIX, image_class

pkg = Package(sys.argv[1])
bm = {p: (o, s) for p, o, s in pkg.index('BMap')}
chrome, bg, accent = [], [], []
for n in sorted(pkg.ids):
    pid = pkg.ids[n]
    if pid not in bm or not n.startswith(BMAP_PREFIX):
        continue
    fmt = pkg.u16(DATA + bm[pid][0])
    if fmt in (4, 8):
        continue
    {'bg': bg, 'accent': accent, 'chrome': chrome}[image_class(n)].append((pid, n))
colr = [(pid, n, v) for pid, n, v in pkg.colr() if not n.startswith(COLR_KEEP_PREFIX)]

with open(sys.argv[2], 'w') as f:
    f.write('/* generated by host/gen_theme_data.py from the OS names table; do not edit */\n')
    f.write('/* chrome images: greys invert, Apple blue becomes the accent */\n')
    f.write('static const uint32_t theme_bmap_chrome[%d] = {\n' % len(chrome))
    for pid, n in chrome: f.write('    0x%08x, /* %s */\n' % (pid, n))
    f.write('};\n/* backgrounds: luminance squeezed into the dark range */\n')
    f.write('static const uint32_t theme_bmap_bg[%d] = {\n' % len(bg))
    for pid, n in bg: f.write('    0x%08x, /* %s */\n' % (pid, n))
    f.write('};\n/* accent icons: every coloured pixel takes the accent hue, in both themes */\n')
    f.write('static const uint32_t theme_bmap_accent[%d] = {\n' % len(accent))
    for pid, n in accent: f.write('    0x%08x, /* %s */\n' % (pid, n))
    f.write('};\n/* COLR entries the dark theme changes (stock value in the comment) */\n')
    f.write('static const uint32_t theme_colr[%d] = {\n' % len(colr))
    for pid, n, v in colr: f.write('    0x%08x, /* %s #%06X */\n' % (pid, n, v))
    f.write('};\n')
print('%d chrome images, %d backgrounds, %d accent icons, %d colours' % (len(chrome), len(bg), len(accent), len(colr)))
